name: Check code style

on:
  push:
    paths:
      - .clang-format
      - "*.cpp"

  pull_request:
    paths:
      - .clang-format
      - "*.cpp"

jobs:
  check-format:
    runs-on: ubuntu-24.04
    env:
      CLANG_VERSION: 20
    steps:
      - uses: actions/checkout@v7

      - name: Setup LLVM repository
        run: |
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
          sudo add-apt-repository -y "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-${CLANG_VERSION} main"

      - name: Install clang-format
        run: sudo apt update -q && sudo apt install -yq clang-format-${CLANG_VERSION}

      - name: Check code style
        run: clang-format-${CLANG_VERSION} -n -style=file --Werror *.cpp
